### ISSUE TITLE
Focus on input box will zoom in the whole page under mobile web

### ISSUE THREAD

**Issue by wanderyt** [wanderyt/my-wacai#98]
[Disable Auto Zoom in Input “Text” tag - Safari on iPhone](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone)

## Reason

The browser will zoom if the font-size is less than **16px** and the default font-size for form elements is **11px** (at least in Chrome and Safari).

### CSS

```css
input[type="color"],
input[type="date"],
input[type="datetime"],
input[type="datetime-local"],
input[type="email"],
input[type="month"],
input[type="number"],
input[type="password"],
input[type="search"],
input[type="tel"],
input[type="text"],
input[type="time"],
input[type="url"],
input[type="week"],
select:focus,
textarea {
  font-size: 16px;
}
```

### HTML Meta Configuration

Prevent Safari from automatically zooming in on text fields during user input without **disabling the user’s ability** to pinch zoom. Just add maximum-scale=1 but leave out the user-scale attribute.

```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
```
